repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  # https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          # compatibility with black
          # E203 whitespace before ':'
          # E741 ambiguous variable name 'I'
          # W503 line break before binary operator
          - "--max-line-length=80"
          - "--select=B950"
          - "--ignore=E203,E501,E741,E701,W503"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
       - id: mypy
         additional_dependencies: [types-PyYAML==6.0.12.20250516]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'PYTHONPATH=./ .venv/bin/pytest tests'
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
